apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: aishelm@hotmail.com  # Replace with your email
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        azureDNS:
          clientID: ${AZURE_CLIENT_ID}
          clientSecretSecretRef:
            name: azure-dns-secret
            key: client-secret
          subscriptionID: ${AZURE_SUBSCRIPTION_ID}
          tenantID: ${AZURE_TENANT_ID}
          resourceGroupName: ${AZURE_DNS_RESOURCE_GROUP}
          hostedZoneName: aimbis.com
          environment: AzurePublicCloud 